# LinearRegression with Cross validation

In [2]:
# import library
import numpy as np
from sklearn.linear_model import LinearRegression

In [1]:
pip install scikit-learn==1.1.3

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_boston

In [6]:
from sklearn.metrics import mean_absolute_error

In [8]:
import pandas as pd
import numpy as np

In [9]:
data_url = "http://lib.stat.cmu.edu/datasets/boston"

In [16]:
raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
target = raw_df.values[1::2, 2]

In [18]:
raw_df.head()

0      1      2    3      4      5     6       7    8      9     10
0    0.00632  18.00   2.31  0.0  0.538  6.575  65.2  4.0900  1.0  296.0  15.3
1  396.90000   4.98  24.00  NaN    NaN    NaN   NaN     NaN  NaN    NaN   NaN
2    0.02731   0.00   7.07  0.0  0.469  6.421  78.9  4.9671  2.0  242.0  17.8
3  396.90000   9.14  21.60  NaN    NaN    NaN   NaN     NaN  NaN    NaN   NaN
4    0.02729   0.00   7.07  0.0  0.469  7.185  61.1  4.9671  2.0  242.0  17.8

In [19]:
data

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [20]:
target

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [21]:
x_train,x_test,y_train, y_tset = train_test_split(data,target, train_size=.7)

In [22]:
linreg = LinearRegression()

In [23]:
linreg.fit(x_train,y_train)

LinearRegression()

In [28]:
y_pred = linreg.predict(x_test)

In [29]:
mean_absolute_error(y_tset, y_pred)

3.4342988625074784

In [31]:
from sklearn.model_selection import cross_val_score

In [35]:
x = boston.data
y = boston.target

In [36]:
multireg = LinearRegression()

multireg.fit(x,y) # not important

LinearRegression()

In [37]:
cross_val_score (multireg,x,y,cv=5)

array([ 0.63919994,  0.71386698,  0.58702344,  0.07923081, -0.25294154])

In [38]:
cross_val_score (multireg,x,y,cv=5).mean()

0.35327592439588484

In [44]:
lin_score = cross_val_score (multireg,x,y,cv=5, scoring= 'neg_mean_absolute_error') # becouse the nagative value

In [45]:
lin_score_n = -lin_score

lin_score_n

array([2.62190565, 3.90725478, 4.386606  , 5.57073637, 4.76333993])

In [46]:
np.mean(lin_score_n)

4.249968544192522